### ISSUE TITLE
关于Marboo新版本的问题

### ISSUE THREAD

**Issue by amoblin** [ubinexy/PKM#1]
关于 未打开编辑的笔记和编辑保存后的笔记，在Marboo中预览效果不一致的问题，我猜测可能是旧版本Marboo中CSS配置导致的。当保存后，Marboo会使用目前的CSS配置来重新生成HTML页面。当然你也可以在选中文件后按r来刷新笔记。

也可以通过修改配置文件marboo_config.json来自定义界面，比如修改HTML模板，CSS文件等。

**Comment by ubinexy** [comment]
尝试修改了 media/css/marboo.css 中的
```
body {
background-color: #eeeeee;
color: black;
}
````
但只有 “未编辑过的笔记” 受影响。

**Comment by ubinexy** [comment]
附两张图来帮助描述问题：
第一张是没编辑前的，后一张是编辑后的。
即便`media/css/marboo.css` 是按第一张配置的。

![2015-03-28 18 03 40](https://cloud.githubusercontent.com/assets/4075671/6880606/01cc30a2-d576-11e4-8c07-20204d5165a2.png)
![2015-03-28 18 04 17](https://cloud.githubusercontent.com/assets/4075671/6880608/12fc00fa-d576-11e4-8f81-13ba7b4eb742.png)

**Comment by amoblin** [comment]
在浏览器中打开，审查元素看一下。除了marboo.css 以外，还有其他css，把其他css删掉排查一下试试。

**Comment by ubinexy** [comment]
能确定影响笔记背景的是 marboo.css
未编辑的笔记用的是 `/.media/css/marboo.css`
编辑后的笔记用的是 `/media/css/marboo.css`
```html
 <link rel="stylesheet" type="text/css" href="/.media/css/marboo.css" media="screen">
```
我想把编辑过的笔记修改成未编辑过的css样式，所以修改了本地唯一的 `.media/css/marboo.css`，但不起作用。如果没法修改的话，我就不折腾了。虽然是个小问题，感谢 amoblin 不厌其烦的指导。

**Comment by amoblin** [comment]
哦，找到原因了。看一下模板文件.media/views/marboo.html，修改里面的css 链接为希望的文件路径即可。

**Comment by ubinexy** [comment]
我弄好了，修改 css 链接的方法有效，感谢！
